import { PDFDocument, rgb, StandardFonts } from "pdf-lib";
import { NextResponse } from "next/server";

export async function POST(req) {
  const { name, company, date, docType, userPassword, ownerPassword } =
    await req.json();

  if (!userPassword || !ownerPassword) {
    return NextResponse.json(
      { error: "Both User & Owner passwords required" },
      { status: 400 }
    );
  }

  if (ownerPassword !== process.env.PDF_OWNER_PASSWORD) {
    return NextResponse.json(
      { error: "Owner password incorrect" },
      { status: 401 }
    );
  }

  const pdfDoc = await PDFDocument.create();
  pdfDoc.setTitle("CS Legal Document");
  pdfDoc.setSubject("Generated by CS System");

  const page = pdfDoc.addPage([595, 842]);
  const { width } = page.getSize();
  const font = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  page.drawText("S K Dwivedi & Associates", {
    x: width / 2 - 150,
    y: 780,
    size: 24,
    font,
    color: rgb(0, 0, 0.5),
  });
  page.drawText("Company Secretary | Legal Documents", {
    x: width / 2 - 150,
    y: 760,
    size: 12,
    font,
    color: rgb(0, 0, 0.3),
  });

  const templates = {
    board: `BOARD RESOLUTION\n\nCompany: ${company}\nDate: ${date}\n\nResolved that the Board approve the matters as per Companies Act.\n\nCertified true copy,\nCS`,
    agm: `ANNUAL GENERAL MEETING RESOLUTION\n\nCompany: ${company}\nDate: ${date}\n\nResolved in AGM that...\nCertified true copy,\nCS`,
    mgt7: `FORM MGT-7\nAnnual Return of ${company}\nDate: ${date}\n\nVerified by CS.`,
    aoc4: `FORM AOC-4\nFinancial Statements of ${company}\nDate: ${date}\n\nCertified true copy by CS.`,
    dir12: `FORM DIR-12\nAppointment/Resignation of Director\nCompany: ${company}\nDate: ${date}\n\nCertified true copy by CS.`,
    share: `SHARE CERTIFICATE\nCompany: ${company}\nDate: ${date}\n\n${name} holds shares.\nCertified true copy,\nCS`,
    others: `Other MCA Form\nCompany: ${company}\nDate: ${date}\n\nPrepared and certified by CS.`,
  };

  const content = templates[docType] || "Generated Document";
  const lines = content.split("\n");
  let y = 700;
  const pageFont = await pdfDoc.embedFont(StandardFonts.Helvetica);

  lines.forEach((line) => {
    page.drawText(line, { x: 50, y, size: 12, font: pageFont, color: rgb(0, 0, 0) });
    y -= 20;
  });

  const pdfBytes = await pdfDoc.save({
    passwords: { user: userPassword, owner: ownerPassword },
  });

  return new NextResponse(pdfBytes, {
    status: 200,
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename=${docType}.pdf`,
    },
  });
}